name: ci

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Validate
        run: bash -n status-check.sh

  test:
    runs-on: ubuntu-latest
    needs: validate
    steps:
      - name: tests
        run: echo "Running tests" && exit 0

  package:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generating report.zip
        run: zip -r report.zip . || true

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: report
          path: report.zip
