name: ci

on:
  push:
    branches:
      - main
  pull_request:

env:
  ACTIONS_STEP_DEBUG: true

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Validate
        run: |
          if bash -n status-check.sh; then
            echo "::warning::OK"
          else
            echo "::error::ERRO"
            exit 1
          fi

  test:
    runs-on: ubuntu-latest
    needs: validate
    steps:
      - name: Tests
        run: |
          echo "Running tests" 
          echo "::notice::Tests OK"
          exit 0

  package:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generating report.zip
        run: zip -r report.zip . || true

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: report
          path: report.zip
      
      - name: Summary
        id: summary
        run: |
          echo "### Job Summary" >> $GITHUB_STEP_SUMMARY
          echo "- OS: \`${{ runner.os }}\`" >> $GITHUB_STEP_SUMMARY
          echo "- Branch: \`${{ github.ref_name }}\`" >> $GITHUB_STEP_SUMMARY
          echo "- Result: Tests Ok" >> $GITHUB_STEP_SUMMARY
          echo "- Artefact: [Download report.zip](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})" >> $GITHUB_STEP_SUMMARY